services:
  - type: web
    name: diabetes-prediction-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app_simple:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120 --log-level info
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHONUNBUFFERED
        value: "1"
    healthCheckPath: /health
